import { ObjectLiteral } from "../components/typings/object";

export const webSocketMessages: ObjectLiteral<string, string> = {
	SERVER_CONNECTION_OPENED: "SERVER_CONNECTION_OPENED",
	CLIENT_CONNECTION_OPENED: "CLIENT_CONNECTION_OPENED",
	SERVER_LISTENING: "SERVER_LISTENING",
	CLIENT_LISTENING: "CLIENT_LISTENING",
	SERVER_ACKNOWLEDGED: "SERVER_ACKNOWLEDGED",
	CLIENT_ACKNOWLEDGED: "CLIENT_ACKNOWLEDGED",
	READY_TO_SEND: "READY_TO_SEND",
	READY_TO_RECEIVE: "READY_TO_RECEIVE",
	SENDING_RECIPE: "SENDING_RECIPE",
	RECIPE_RECEIVED: "RECIPE_RECEIVED",
	RECIPE_VERIFIED: "RECIPE_VERIFIED",
	SERVER_RECIPE_PARSE_SUCCESS: "SERVER_RECIPE_PARSE_SUCCESS",
	SERVER_RECIPE_PARSE_FAILURE: "SERVER_RECIPE_PARSE_FAILURE",
	URL_RECEIVED: "URL_RECEIVED",
	SENDING_URL: "SENDING_URL",
	SERVER_CONNECTION_CLOSED: "SERVER_CONNECTION_CLOSED",
	CLIENT_CONNECTION_CLOSED: "CLIENT_CONNECTION_CLOSED",
} as const;
