CREATE ROLE chef WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'chef';
CREATE ROLE root WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'root';

CREATE ROLE backup WITH LOGIN ENCRYPTED PASSWORD 'backup';


--\c chef chef
CREATE DATABASE recipebox WITH OWNER chef;

GRANT ALL PRIVILEGES ON DATABASE recipebox TO chef;

\connect recipebox;
CREATE SCHEMA kitchen AUTHORIZATION chef;
GRANT ALL ON SCHEMA kitchen TO chef;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO chef;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA kitchen TO chef;

ALTER DEFAULT PRIVILEGES IN SCHEMA kitchen GRANT ALL ON TABLES TO chef;
ALTER DEFAULT PRIVILEGES IN SCHEMA kitchen GRANT ALL ON SEQUENCES TO chef;
ALTER DEFAULT PRIVILEGES IN SCHEMA kitchen GRANT ALL ON FUNCTIONS TO chef;



CREATE ROLE taster WITH LOGIN ENCRYPTED PASSWORD 'taster';
CREATE DATABASE test WITH OWNER taster;

\connect test
CREATE SCHEMA test AUTHORIZATION taster;
GRANT ALL ON SCHEMA test TO chef, taster;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA test TO chef, taster;
ALTER DEFAULT PRIVILEGES IN SCHEMA test GRANT ALL ON TABLES TO chef, taster;
ALTER DEFAULT PRIVILEGES IN SCHEMA test GRANT ALL ON SEQUENCES TO chef, taster;
ALTER DEFAULT PRIVILEGES IN SCHEMA test GRANT ALL ON FUNCTIONS TO chef, taster;

ALTER USER chef SET search_path TO kitchen;
ALTER USER taster SET search_path TO test;

ALTER DATABASE recipebox SET SEARCH_PATH TO kitchen;
ALTER DATABASE test SET SEARCH_PATH TO test;
--CREATE ROLE writer;
--GRANT writer TO chef, taster;
--ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO writer;
