CREATE ROLE chef WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'chef';
CREATE ROLE root WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'root';
CREATE DATABASE chef WITH OWNER 'chef';
CREATE ROLE taster WITH LOGIN ENCRYPTED PASSWORD 'taster';
CREATE ROLE backup WITH LOGIN ENCRYPTED PASSWORD 'backup';

-------------------
\c chef chef
CREATE DATABASE recipebox WITH OWNER 'chef';

--GRANT CONNECT ON DATABASE recipebox TO chef,taster;
GRANT ALL PRIVILEGES ON DATABASE recipebox TO chef;

--\connect recipebox;
--\connect - chef;

CREATE SCHEMA kitchen AUTHORIZATION chef;
GRANT ALL ON SCHEMA public, kitchen TO chef;

--CREATE SCHEMA test AUTHORIZATION taster;
--GRANT USAGE ON SCHEMA test TO taster;

--ALTER DATABASE recipebox SET search_path TO kitchen,test,public;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO chef;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA kitchen TO chef;
--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA kitchen,public TO chef;
--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO taster;

CREATE ROLE writer;
GRANT writer TO chef, taster;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO writer;
